### ISSUE TITLE
@import '3-sections/-sections-dir' (Not working)

### ISSUE THREAD

**Issue by dmenu** [DevTips/Artists-Theme#73]
Hello all,

I'm french so I'm sorry for my english :smile: 

I started the last 3 days the DevTips Artitsit template tutorial. After several hours to install all the programs I'm now in the coding phase (part 4).

I created the same structure and my {% include header.html %} is working but for the CSS part I've some challenge. 

If I add this code in my all.sass the css works
> all.sass
```
---
---
body
	background-color: red
```

but if I add these the CSS NOT working, in the _site the file 'all' in not converting to .css but stay as a .sass

> all.sass
```
@import '3-sections/-sections-dir'
```

> _-sections-dir.sass
```
@import 'header'
```
> header.sass
```
body 
	background-color: pink
```

Here is my configuration file so far:
>_config.yml
```
# Build settings
port: 8000
sass:
	sass_dir: _sass
```

Thanks for your help,
Damien

**Comment by wiafe** [comment]
I hit this at the beginning also, try putting this in your _config.yml:
```SASS
markdown: kramdown
permalink: pretty
highlighter: rouge

port: 8080

include: ['_includes/work']
exclude: ['the_design.psd']

sass:
  sass_dir: assets/css
  style: :nested
```

It's what I had to do before it worked for me.

**Comment by dmenu** [comment]
@wiafe Thanks for your help but I still not working ....

also when I restart Jekyll here is the message that I have
```
MacBook-Damien:Website taber$ jekyll serve --watch
jekyll 2.5.3 | Error:  (/Users/taber/Website/_config.yml): found character that cannot start any token while scanning for the next token at line 6 column 1
```
>_config.yml
```
markdown: kramdown
permalink: pretty
highlighter: rouge
port: 8000
sass:
	sass_dir: assets/css
	style: :nested
```

Thanks,
Damien

**Comment by wiafe** [comment]
@dmenu Take out the highlighter I use that because I'm using jekyll on a PC.

**Comment by dmenu** [comment]
@wiafe I style have the same error... :disappointed:

**Comment by wiafe** [comment]
@dmenu Can you upload or share with me what you have so I can look over it?

**Comment by dmenu** [comment]
@wiafe I sent you an eamil with my skyppe ...

**Comment by wiafe** [comment]
@dmenu Sadly don't have skype on here can you upload it to google drive by chance and share?

**Comment by dmenu** [comment]
Here is the code :)

**Comment by dmenu** [comment]
@wiafe I'll sent you a Zip on your email adresse :)

**Comment by wiafe** [comment]
Go into index.html and type the --- up on top
```HTML
---
---
<!DOCTYPE html>
```

**Comment by dmenu** [comment]
I still have the have the same problem with the  _config.yml ...

:/

**Comment by dmenu** [comment]
After several tests I saw that the .scss is working but not the .sass .. ??

**Comment by zeldanerd** [comment]
Bonjour @dmenu is possible for you to send me your code so i can look over and see if i find the error.

**Comment by dmenu** [comment]
@zeldanerd Yes do you have an email adress ? thanks, Damien

**Comment by zeldanerd** [comment]
Yes you can contact me at zeldanerd123@hotmail.com

**Comment by wiafe** [comment]
@dmenu @zeldanerd were you guys able to figure it out?

**Comment by zeldanerd** [comment]
@waife @dmenu I still haven't but he has scss working. do want to code using .sass dmenu?

**Comment by zeldanerd** [comment]
honestly if he wants to code his css .sass it's an easy fix to make it modular

**Comment by dmenu** [comment]
@wiafe @zeldanerd at the moment I'm not able to find the solution for the .sass. My end goal is to have a website in html + css. Thanks for your help. Damien

**Comment by travisneilson** [comment]
Hey guys. Thanks for being so helpful. This is amazing. I am so appreciative :)

Can I have a look at your project?

**Comment by dmenu** [comment]
@travisneilson Thanks for your help Travis. I just sent you an email .. Best regards, Damien

**Comment by travisneilson** [comment]
Got your email. Here is my take on it. I made a video.
http://youtu.be/98bfoRDligs

Hope its helpful :)

**Comment by dmenu** [comment]
@travisneilson @wiafe @zeldanerd Thanks all for your help ... I'll continue all the serie ...  :+1: :)

**Comment by travisneilson** [comment]
Anytime! I'm glad I can help. And it was really cool to see others rushing in to support also. Thanks @zeldanerd and @wiafe — you rock!

**Comment by zeldanerd** [comment]
@dmenu @dmenu No problem, I love to help others. Dmenu, If you ever need anymore help don't hesitate to ask for help. Travis its a pleasure, if it wasn't from all the help you have provide us, I don't think I would have even know how to fix his issue. :+1: :)

**Comment by takhunov44** [comment]
HI Everyone,
Having the same problem. Any help would be appreciated.
Thanks.
