### ISSUE TITLE
Conversion Error with Bourbon?

### ISSUE THREAD

**Issue by angelocordon** [DevTips/Artists-Theme#74]
Getting this error, which looks like it 's from Bourbon in
/assets/css/1-tools/bourbon/helpers/_linear-angle-parser.scss

Conversion error: Jekyll::Converters::Sass encountered an error while converting 'assets/css/main.sass':
                    Invalid CSS after " webkit-image": expected ")", was ": -webkit- + $p..." on line 21

Not too familiar with Bourbon, is this just a typo?

**Comment by niklasravnsborg** [comment]
@angelocordon Sorry for responding so late. Did your problem resolve? Sounds like you have to update Jekyll and Sass to get the newest Sass Compilation Engine. I would try `sudo gem update sass jekyll`. My Sass (`sass -v`) is `Sass 3.4.16 (Selective Steve)` and it works. Hope this helps if you couldn't resolve this by yourself.
