### ISSUE TITLE
New website, thanks all

### ISSUE THREAD

**Issue by dmenu** [DevTips/Artists-Theme#75]
Hello all,

after a couple of weeks I'm glad to present you my website based on this "programme" : www.2BProud.fr

off course he's maybe not perfect but it's my first site ! I'll be more than happy to get your feedbacks, to improve design, code etc ... 

Sorry I'm from Paris so the website is French. The idea of the website for me is just to give a "showcase", of my youtube chanel about fitness (openning in 2-3weeks).

Happy Easter !!
Damien

**Comment by travisneilson** [comment]
Awesome! Congrats!

**Comment by musiclover23** [comment]
Awesome Website!!! It looks great!

**Comment by bengalurean** [comment]
Beautiful! Congratulations.

**Comment by nicollehahn** [comment]
Congratulations!  Now I am inspired.  It looks wonderful.
