### ISSUE TITLE
Jekyll Project?

### ISSUE THREAD

**Issue by Lego2012** [DevTips/Artists-Theme#81]
Hi Travis,
in the repo I see only the gh-pages branch. Is there a master branch available as well for rebuilding the project locally?

Tnx and best regards from Germany,
Leo

**Comment by niklasravnsborg** [comment]
@Lego2012 The `gh-pages` branch is the main branch here. The naming is like that so that GitHub can be used as the hosting service. You can use the project locally without any problems by cloning it. :relaxed:

**Comment by Lego2012** [comment]
Tnx, Niklas, you're right. I didn't look carefully and thought this is the final build.

Regards, Leo

**Comment by niklasravnsborg** [comment]
@Lego2012 Kein Ding Leo! :de:
