### ISSUE TITLE
Re: Mixed Content Error

### ISSUE THREAD

**Issue by crikeli** [DevTips/Artists-Theme#91]
Hey Everyone, 

Thanks a lot for making this theme available. It has been a huge help . I just finished pushing my modified code to github and generated a gh page based website. However, when click on a picture in the "work" section, I get this error in my browser console.

"Mixed Content: The page at 'https://crikeli.github.io/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://crikeli.github.io/work/proj-2/'. This request has been blocked; the content must be served over HTTPS." . 

Do you know if any one has ran into this issue? And if so, how did they solve it?
I'd greatly appreciate any help!

Thanks :)

**Comment by niklasravnsborg** [comment]
@crikeli Tricky one... Fixed this in https://github.com/DevTips/Artists-Theme/commit/5ec5c024ef0a3d5e1e41053b6cada69bf918d7aa, https://github.com/DevTips/Artists-Theme/commit/698570d1c94040f8435440cd4de3f726a82933a6 and https://github.com/DevTips/Artists-Theme/commit/b64eb5bee7560b6882e7749d77995121ebd091ef.

I would also advice you to change your GitHub Pages Settings to: 
<img width="756" alt="screen shot 2016-11-01 at 23 12 18" src="https://cloud.githubusercontent.com/assets/6717303/19909586/a9e014d2-a088-11e6-8488-ea20a5944dfd.png">

Let me know if this helps. :)

**Comment by crikeli** [comment]
@niklasravnsborg You are a lifesaver! I was considering taking it apart today, because up until yesterday, I was only trying to change the content security policies. This certainly helped solve the issue! 

Thanks man :)

**Comment by niklasravnsborg** [comment]
@crikeli Glad to hear that! 👍 Let me know if you have any further questions ☺️

**Comment by crikeli** [comment]
Hey @niklasravnsborg, I got an error with my layout and I've opened another issue. One other person also got that error. Do you mind checking it out and giving your input on it?
Here is the link:
https://github.com/DevTips/Artists-Theme/issues/93

Thanks!
