### ISSUE TITLE
Why my code does not work 100%? (Code newbie here)

### ISSUE THREAD

**Issue by zhouxiang19910319** [DevTips/Artists-Theme#92]
I have watched debTips for a while already.
Also at the same time learning a little bit of HTML and CSS at FreeCodeCamp.
I was trying to duplicate Travis's "Artist-theme" personal portfolio. 
However I was stuck here, I did not know why my code does not work. 
Here are a few things I found out didn't work.

- The logo did not show up at all.

- The navigation part (those 4 tabs) can only be moved from left to right of the screen. I can only change the margin of them. Other than that, you can see in the screen shots everything did not work. 

Any suggestions are welcomed. 
Thanks! 
![screen shot 2016-11-02 at 8 38 09 am](https://cloud.githubusercontent.com/assets/9369928/19912845/92d2a21e-a0d8-11e6-9de7-c5b337dabdb8.png)

**Comment by niklasravnsborg** [comment]
Hey there! This is not exactly an issue with this project. May you ask the community over at YouTube: https://www.youtube.com/user/DevTipsForDesigners. 

Also I would advice you to exactly follow Travis in his tutorial series: https://www.youtube.com/watch?v=T6jKLsxbFg4&list=PLqGj3iMvMa4KQZUkRjfwMmTq_f1fbxerI. Codepen may not be the right tool to use in this case.
