### ISSUE TITLE
Layout changes on live site as compared to the local version

### ISSUE THREAD

**Issue by crikeli** [DevTips/Artists-Theme#93]
Hey all,

I have no idea why this is happening, but it is :( . I am able to render the "work" section on the website perfectly while I am testing locally: 
![screen shot 2016-12-12 at 12 32 54 am](https://cloud.githubusercontent.com/assets/8507995/21092688/c69a72e0-c002-11e6-90a9-f3902885d800.png)
![screen shot 2016-12-12 at 12 33 07 am](https://cloud.githubusercontent.com/assets/8507995/21092690/ca70afc4-c002-11e6-9638-65055e44c575.png)

However, after I publish the site, the layout gets completely messed up
![screen shot 2016-12-12 at 12 33 26 am](https://cloud.githubusercontent.com/assets/8507995/21092711/eb127096-c002-11e6-8a3f-6c7ba295c7d4.png)
![screen shot 2016-12-12 at 12 33 34 am](https://cloud.githubusercontent.com/assets/8507995/21092714/ee0d58d8-c002-11e6-92e3-c7ead3f033b8.png)

--------

Has anyone experienced this? If so, any solutions?

Thanks alot for reading and for the help in advance! 

P.S The code resides here : https://github.com/crikeli/crikeli.github.io

**Comment by katalin2003** [comment]
Did you use the developer tools?
Looks like missing HTML.

**Comment by crikeli** [comment]
Thanks for your reply Katalin!

I did use them, but how can it be missing html if it renders correctly locally, but not when published?

**Comment by katalin2003** [comment]
I'm sorry.
What I meant is to inspect the published site for any missing HTML or CSS,
by comparing with your local version.

We can narrow down from there.

**Comment by crikeli** [comment]
hmmm, I don't see how the code would be different, but I will double check. Thanks though :)

**Comment by crikeli** [comment]
Apparently, when I see the debugging console, a new file is generated called *style.css. It does not exist anywhere in my repository, but it spawns for some reason.

Here is the image of the file.
![screen shot 2016-12-12 at 3 56 40 am](https://cloud.githubusercontent.com/assets/8507995/21098735/6b22ddd6-c01f-11e6-83d3-53639e2855de.png)


Here is a pic of the file when I delete its contents. (the layout gets fixed)
![screen shot 2016-12-12 at 3 57 22 am](https://cloud.githubusercontent.com/assets/8507995/21098737/706aef68-c01f-11e6-9b9a-614bb95c044a.png)

-------------

Any ideas of how I can get rid of a non-existent file? :/

Thanks again!

**Comment by TBT-techno** [comment]
+1 I'm experiencing the same bug on the live (github hosted) versus local version of my site as well.

**Comment by crikeli** [comment]
Any luck finding a solution? @TBT-techno

**Comment by BuckyMaler** [comment]
@crikeli @TBT-techno I experienced the same issue. The ajax request for the work content was wrapping the requested HTML in non-specified HTML. By that I mean, there was a head and body, when only a raw snippet was being requested. Unfortunately, I can't shed much light on why the issue was occurring, but my solution was to push the production files (i.e. _site/) to the master branch. I of course would have preferred to have the development on master, and production on gh-pages, but for the USERNAME.github.io repo I believe GitHub displays the contents from the master branch. Again, I wish I could shed more light on the issue. I hope that helps.

**Comment by crikeli** [comment]
@BuckyMaler You are right, that is exactly what happened. It still does not make sense what caused the error, but your solution worked! Thanks :)

**Comment by Sayan98** [comment]
@BuckyMaler besides removing `_site/` from `.gitignore` did you do anything else? I can't get this working. 📦
