### ISSUE TITLE
Add button to go back up at the end of the work section

### ISSUE THREAD

**Issue by lucaslampe** [DevTips/Artists-Theme#94]
Might be handy to add a button at the end of the work section, so that one doesn't need to scroll back up all the way to view the other work.

![GIF](http://i.imgur.com/MkazByP.gif "Sample GIF")

**Comment by niklasravnsborg** [comment]
@lucaslampe Hey this is a great idea. You are welcome to open a pull request that adds that functionality. I'm closing this for now.
