### ISSUE TITLE
Is it the design or in the 'clients' section the quotes are overlapping with the text(quotes)

### ISSUE THREAD

**Issue by surajmandalcell** [DevTips/Artists-Theme#96]

**Comment by niklasravnsborg** [comment]
@surajmandalcell Hey there. Can you provide a screenshot of the issue?

**Comment by surajmandalcell** [comment]
## Sure!
![screenshot from 2017-02-16 22-57-58](https://cloud.githubusercontent.com/assets/11650177/23032735/789aa89e-f49b-11e6-9a08-3477f40543dd.png)

There you go!

**Comment by jannishinkelmann** [comment]
@surajmandalcell as you can see in the design (picture), it is intended this way.

**Comment by surajmandalcell** [comment]
Hum....okey thanks. Ill close this issue now then
